version: '2'
services:
  httpd:
    build: ./docker/httpd/
    image: my/apache2.4
    container_name: 'httpd'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./src:/var/www/www.example.com/

  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    image: my/php7.2
    container_name: 'php'
    tty: true
    ports:
      - '9000:9000'
    volumes:
      - ./src:/var/www/www.example.com/
      - /var/www/www.example.com/vendor/
      - /var/www/www.example.com/node_modules/
    depends_on:
      - mysql

  mysql:
    build: ./docker/mysql/
    image: my/mysql5.7
    container_name: 'mysql'
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_ROOT_PASSWORD=development
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/example.sql:/docker-entrypoint-initdb.d/example.sql

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

volumes:
  mysql-data:
    driver: local